# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "2.7"
  - "2.6"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -r requirements-test.txt
  - pip install coveralls

# command to run tests, e.g. python setup.py test
script: python ./filtered_feed/testproject/manage.py test

# command to run after success of tests
after_success: coveralls